### ISSUE TITLE
GH workflow secrets

### ISSUE THREAD

**Issue by APN-Pucky** [fsphys-muenster/ersti-fibel#135]
SCIEBO_SHARELINK_ID might be stolen by someone via workflow PR

**Comment by 2xB** [comment]
Is that true? Can external PRs run modified workflows and extract repository secrets? I think they are run with the unmodified workflow.

**Comment by 2xB** [comment]
We are using the `pull_request` and not the `pull_request_target` workflow trigger, so I think we should be safe.

**Comment by APN-Pucky** [comment]
Ah, ohne write access muss erst aproved werden: https://github.com/fsphys-muenster/ersti-fibel/pull/144
