### ISSUE TITLE
Why sciebo upload vs github artifacts?

### ISSUE THREAD

**Issue by APN-Pucky** [fsphys-muenster/ersti-fibel#138]
Sciebo is already very poluted with 10+7+20+12 GB of data. Github artifacts can easily time out after 1 week

**Comment by 2xB** [comment]
We don't have the licenses to publish content containing some of the comics (hence they are in the "private" sub-repository). We therefore never published the complete Ersti-Fibel except behind a login. In the Sciebo we have something in the order of 1 TB of storage space, so I'm not afraid that we occupy too large amounts of storage there. Unneeded artifacts can of course also easily be deleted from Sciebo manually whenever one wishes.
